export enum APIvars {
    APIdomain = '',
    APIlogin = 'login',
    CHECK_IF_TAKEN = 'signup/checkiftaken',
    APIemailOTP = 'signup/emailverification',
    APIsignup = 'signup',
    APIgoogleSignup = 'https://apis.google.com/js/platform.js',
    APIrecaptcha = 'https://www.google.com/recaptcha/api.js',
    APIrecaptchaKey = '6LflNcUZAAAAABuL1BkTS27rP3t2iuI7FMgrC0WU',
    APIallowAll = '*',
    APIattemptLogin = 'login/attempt',
    APIattemptLogin2 = 'login/attempt2',
    GOOGLE_0AUTH_CLIENT_ID = '1063064480579-4pqt0259eqsu2epkctrchjk31q5j8ani.apps.googleusercontent.com', // '206033993886-qqam7i8l0egv1t8iih63hnqiut8c932e.apps.googleusercontent.com'
    FACEBOOK_APP_ID = '',
    GET_HASHTAGS  = 'mentions',
    GET_DP = 'resources/getdp',
    SET_DP = 'resources/setdp',
    GET_DP_OF_USER = 'resources/dpofuser',
    GET_COVER_OF_USER = 'resources/coverofuser',
    REMOVE_DP = 'resources/dp',
    GET_COVER = 'resources/getcover',
    SET_COVER = 'resources/setcover',
    REMOVE_COVER = 'resources/cover',
    SEARCH_USER = 'search/user',
    SEARCH_USER_FOR_MENTION = 'search/mention',
    NOW_PLAYING = 'nowplaying',
    REMOVE_NOW_PLAYING = 'nowplaying/remove',
    GET_GAMELIST = 'nowplaying/gamelist',
    GET_GAMEDATA = 'gamedata/getGame',
    SET_USER_GAMEDATA = 'gamedata/saveusergamedata',
    GET_USER_GAMEDATA = 'gamedata/saveusergamedata',
    GET_USERDATA = 'signup/getuserdata',
    SET_USERDATA = 'signup/setuserdata',
    GAMEDATA = 'gamedata',
    GET_FOLLOW_STATUS_OF = 'resources/getfollowstatus',
    SET_FOLLOWING = 'resources/setfollowing',
    GET_FOLLOWDATA = 'resources/getfollowdata',
    CONFIRM_OTP = 'signup/confirmOTP',
    RECOVERY = 'recovery',
    CHANGE_PASSWORD = 'recovery/newp',
    SET_NEW_FAV = 'gamedata/addfavorite',
    GET_IMAGE = 'resources/getImage',
    SEND_MESSAGE = 'resources/message',
    GET_MESSAGE_PINGS = 'messages/messagepings', 
    GET_UNSEEN_MESSAGE_COUNT = 'messages/unseenmessagecount',
    GET_BRIEF_MESSAGES = 'messages/briefmessages',
    SET_LOCATION = 'signup/location',
    GET_USERDATA_BY_ID = 'signup/getuserdatabyid',
    GET_CHATROOM_ID_BY_USERS = 'messages/getchatroomid',
    SAVE_MESSAGE = 'messages',
    GET_ALL_MESSAGES = 'messages/getall',
    GET_MESSAGES_BY_ID = 'messages/getbyid',
    CLEAR_CONVO = 'messages/clearconvo',
    DELETE_CONVO = 'messages/deleteconvo',
    GET_FOLLOWERS = 'follow/getfollowers',
    GET_FOLLOWING = 'follow/getfollowing',
    GET_USERS_AROUND = "signup/getusersbydistance",
    CHECK_USERNAME = 'signup/usernameavailable',
    NOTIFICATIONS = 'notifications',
    NEW_NOTIFICATION_COUNT = 'newnotificationcount',
    EXISTS = 'signup/exists',
    SET_NOTIFICATION_SEEN = 'notifications/notificationseen',
    READ_ALL_NOTIFICATIONS = 'notifications/readall',
    ADD_POST = 'post',
    GET_POSTS = 'post/getposts',
    DELETE_POST_BY_ID = 'post',
    ADD_REMOVE_LIKE = 'post/like',
    SET_POST_IMAGE = 'post/setpostimage',
    GET_POST_MEDIA_BY_ID = 'post/getpostmedia',
    DELETE_DP_OR_COVER = 'resources/deleteuserimage',
    GET_SUGGESTED_USERS = 'search/suggestedusers',
    GET_NP_OF_FOLLOWERS = 'nowplaying/nplistoffollowers',
    REMOVE_FOLLOWER = 'follow/removefollower',
    LIKE_NP = 'nowplaying/likenp',
    DELETE_NP_POST = 'nowplaying/deletenppost',
    GET_WHO_LIKED = 'nowplaying/wholiked',
    ADD_PLAYS = 'nowplaying/addplays',
    NP_POST_WITH_DETAILS = 'nowplaying/postwithdetails',
    ADD_COMMENT = 'nowplaying/addcomment',
    GET_COMMENTS_ON_NP = 'nowplaying/commentsonnppost',
    NP_DELETE_COMMENT = 'nowplaying/deletecomment',
    DELETE_ACCOUNT = 'signup/deleteAccount',
    GET_EULA = 'signup/geteula',
    EULA_CONFIRM = 'agreement/confirm-eula',
    ACTIVE_NOW_PLAYING_USERS = 'nowplaying/activeusers',
    FEEDBACK = 'feedback',
    LAST_ACTIVE = 'signup/lastactive'
}

export enum GlobalContantsEnum {
    RECAPTCHA_SITE_KEY = '6LflNcUZAAAAABuL1BkTS27rP3t2iuI7FMgrC0WU'
}

export enum SocketEventsEnum {
    NEW_NOTIFICATION = 'new-notification',
    NEW_MESSAGE = 'new-message',
    REQUEST_NP_PASSWORD = 'request-np-pwd',
    RESPONSE_NP_PASSWORD = 'response-np-password',
    OPEN_SERVER = ':o:',
}

export enum ErrorMessagesEnum {
    NP_REQUEST_LIMIT_REACHED = 'Max served request limit reached, you\'re in buffer :('
}