export enum APIvars {
    APIdomain = 'http://localhost:3000',
    APIlogin = 'login',
    APIemailOTP = 'signup/emailverification',
    APIsignup = 'signup',
    APIgoogleSignup = 'https://apis.google.com/js/platform.js',
    APIrecaptcha = 'https://www.google.com/recaptcha/api.js',
    APIrecaptchaKey = '6LflNcUZAAAAABuL1BkTS27rP3t2iuI7FMgrC0WU',
    APIallowAll = '*',
    APIattemptLogin = 'login/attempt',
    GOOGLE_PROVIDER = '206033993886-qqam7i8l0egv1t8iih63hnqiut8c932e.apps.googleusercontent.com',
    FACEBOOK_APP_ID = '',
    GET_HASHTAGS  = 'mentions',
    GET_DP = 'resources/getdp',
    SET_DP = 'resources/setdp',
    GET_DP_OF_USER = 'resources/dpofuser',
    GET_COVER_OF_USER = 'resources/coverofuser',
    REMOVE_DP = 'resources/dp',
    GET_COVER = 'resources/getcover',
    SET_COVER = 'resources/setcover',
    REMOVE_COVER = 'resources/cover',
    SEARCH_USER = 'search/user',
    NOW_PLAYING = 'nowplaying',
    REMOVE_NOW_PLAYING = 'nowplaying/remove',
    GET_GAMELIST = 'nowplaying/gamelist',
    GET_GAMEDATA = 'gamedata/getGame',
    SET_USER_GAMEDATA = 'gamedata/saveusergamedata',
    GET_USERDATA = 'signup/getuserdata',
    SET_USERDATA = 'signup/setuserdata',
    GAMEDATA = 'gamedata',
    GET_FOLLOW_STATUS_OF = 'resources/getfollowstatus',
    SET_FOLLOWING = 'resources/setfollowing',
    GET_FOLLOWDATA = 'resources/getfollowdata/',
    CONFIRM_OTP = 'signup/confirmOTP',
    RECOVERY = 'recovery',
    CHANGE_PASSWORD = 'recovery/newp'
}

export enum GlobalContantsEnum {
    RECAPTCHA_SITE_KEY = '6LflNcUZAAAAABuL1BkTS27rP3t2iuI7FMgrC0WU'
}